### ISSUE TITLE
Revisão dos débitos da 1ª entrega - Documentação/MDS

### ISSUE THREAD

**Issue by pedrohelias** [mdsreq-fga-unb/2022.1-pets-off-road#10]
# Revisão de débitos
## Realizar a revisão documental solicitada pelo professor. Correção de pontos solicitados e atualização de escopo de MDS.

- [x] Adicionar a experiência de MDS no tópico de Lições, da 1ª entrega.
- [x] Correção do documento, revisão de escopo, entre outros. 

## Prazo para realização: 18/07/2022

**Comment by MattSilverio** [comment]
Revisões feitas no Topico 3 do documento de visão
