### ISSUE TITLE
Revisão dos débitos da 1ª entrega - Documentação/REQ

### ISSUE THREAD

**Issue by pedrohelias** [mdsreq-fga-unb/2022.1-pets-off-road#11]
# Revisão de débitos
## Realizar a revisão documental solicitada pelo professor. Correção de pontos solicitados e atualização de escopo de Requisitos.

- [x] Identificar a engenharia de requisitos no Diagrama Genérico - Verificar os slides disponibilizados com o diagrama de fluxo genérico 
- [x] Planejamento de projeto - Revisar as datas do planejamento de Sprints(alterado agora para duas semanas por sprint), além de completar o planejamento. 

## Prazo para realização: 18/07/2022

**Comment by GabrielMR360** [comment]
Alteração do prazo para realização 14/07 para 18/07
