### ISSUE TITLE
CANVAS MVP e o MVP

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-pets-off-road#27]
**Descrição**
a lista de requisitos funcionais no CANVAS MVP é diferente da lista de requisitos do MVP. Isso está inconsistente. Deveria ser a mesma lista, já que o CANVAS MVP é construído para a definição do MVP.

- [ ] alinhar a consistência entre o CANVAS MVP e o MVP

**Fonte**
https://mdsreq-fga-unb.github.io/2022.1-pets-off-road/canvas/

**Comment by pedrohelias** [comment]
Dúvida: Issue 27: O MVP não era exatamente uma entrega da unidade 2, correto?
Comentário do professor: Não. O MVP era uma das entregas da unidade 2
