### ISSUE TITLE
MVP vs. SAFe

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.1-pets-off-road#30]
**Descrição**
qual a relação entre as funcionalidades registras no MVP e a estrutura do SAFe? Onde as funcionalidades estão representadas na estrutura do SAFe?

**Fonte**
https://mdsreq-fga-unb.github.io/2022.1-pets-off-road/backlog/
https://mdsreq-fga-unb.github.io/2022.1-pets-off-road/canvas/

**Comment by pedrohelias** [comment]
- Sobre a Issue 30: Quando o senhor diz que deve haver relação entre a SAFe e as funcionalidades do MVP, o senhor espera um texto que explique isso ou que as funcionalidades descritas no backlog devem ser as mesmas que colocamos no canvas? Trocamos os nomes mais pra entendimento do que queriamos, mas podemos alterar.
- Comentário do Professor: se vc altera o nome, vc altera o RF. Os adequada uma nomenclatura que não estava adequada. Deve-se manter a consistência entre os dois. Ou seja, o mesmo nome.
